### PR TITLE
Add support for saving the Height and Weight to GSettings

### PR DESCRIPTION
**Pull request by vikdevelop**
Hello, 
I found your app, which I think is useful.

I also think, it would be a very great, if the app remembered the height and the weight values, so I don't need to enter them each time the application is started, so I did it.

The changes include files:
- `data/io.github.philippkosarev.bmi.gschema.xml`
- `src/window.py`
- `src/main.py`

### CODE REVIEW

**Comment by philippkosarev** [comment]
Hey, thank you for the pr :)
Everything looks pretty good. 
The `self.on_value_changed(_scroll="")` line doesn't seem to do anything though, am I missing something?

**Comment by vikdevelop** [comment]
> The self.on_value_changed(_scroll="") line doesn't seem to do anything though, am I missing something?
No, this function shows the BMI result, such as underweight, healthy, overweight, etc.

**Comment by vikdevelop** [comment]
> The self.on_value_changed(_scroll="") line doesn't seem to do anything though, am I missing something?

No, this function shows the BMI result, such as underweight, healthy, overweight, etc., because if it's not there, it will display an incorrect BMI result when run.

**Comment by philippkosarev** [comment]
Yes, but commenting it out doesn't seem to affect the anything.
The `adjustment = Gtk.Adjustment(lower= 10, upper=650, step_increment=1, page_increment=10, value=self.settings["weight"])` line sets the saved value, then before displaying the bmi `self.calc_bmi()` gets called (which takes the just set adjustment value), so it appears that the line is redundant.

**Comment by vikdevelop** [comment]
Ok, I removed the self.on_value_changed(_scroll="") line.

**Comment by philippkosarev** [comment]
Alright then, everything else looks swell. Thanks for the contribution!

**Pull request merged**
